version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: metalcorepy_db
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5887:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: metalcorepy_app
    build: ./app
    command: python3 manage.py runfull 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    
  redis:
    image: redis:7
    container_name: metalcorepy_redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: ./app
    container_name: metalcorepy_celery
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: ./app
    container_name: metalcorepy_celery_beat
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - celery
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  opa:
    image: openpolicyagent/opa:latest
    container_name: metalcorepy_opa
    ports:
      - "8181:8181"
    volumes:
      - ./security:/policy
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--addr=:8181"
      - "/policy"
    restart: unless-stopped

volumes:
  postgres_data:

