version: "3.8"

services:
  web:
    build: ./app
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 --timeout 30 --log-level info core.wsgi:application
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      default:
        ipv4_address: 172.18.1.10

  postgres:
    image: postgres:15
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_ecovista
      POSTGRES_DB: ecovista
    networks:
      default:
        ipv4_address: 172.18.1.20
    ports:
      - "5887:5432"
    volumes:
      - ./databse:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16 