version: "3.8"

services:
  web:
    build: ./app
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 --timeout 30 --log-level info core.wsgi:application
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
