version: "3.8"

services:
  web:
    container_name: metalcorepy_app
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  postgres:
    image: postgres:15
    container_name: metalcorepy_db
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5887:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
      - "8181:8181"
    volumes:
      - ./security:/policy
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policy"
    restart: unless-stopped

volumes:
  postgres_data:

