version: "3.8"

services:
  web:
    container_name: metalcorepy_app
    build: ./app
    command: gunicorn --workers 4 --bind localhost:8000 --timeout 30 --log-level info core.wsgi:application
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  postgres:
    image: postgres:15
    container_name: metalcorepy_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5887:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

