version: "3.8"

services:
  web:
    container_name: metalcorepy_app
    build: ./app
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 --timeout 30 --log-level info core.wsgi:application
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  postgres:
    image: postgres:15
    container_name: metalcorepy_db
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5887:5432"

